name: Java CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOCKER_REPO: java-maven-actions-proj

jobs:

  CI-CD:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build 
      run: mvn -B -DskipTests clean package

    - name: Test
      run: mvn test

    - name: Publish test results
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: target/surefire-reports/*.xml

    - name: Get latest tag
      id: get_tag
      run: |
        latest_tag=$(git describe --tags --abbrev=0)
        echo "LATEST_TAG=$latest_tag" >> $GITHUB_ENV
      
    - name: Build Docker Image
      run: docker build -t $DOCKER_REPO:$LATEST_TAG .

    - name: DockerHub - Auth
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: DockerHub - Push
      run: |
        docker tag $DOCKER_REPO:$LATEST_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_REPO:$LATEST_TAG
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$DOCKER_REPO:$LATEST_TAG

    - name: Version
      run: scripts/bump_ver.sh
      env:  
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Deliver
    #   run: ./jenkins/scripts/deliver.sh
